-- YONETICILER tablosu
-- Bu script'i Oracle'da bir kez calistirin.

CREATE TABLE YONETICILER (
    YONETICI_ID NUMBER(10)    NOT NULL,
    AD          VARCHAR2(100) NOT NULL,
    SOYAD       VARCHAR2(100) NOT NULL,
    DEPARTMAN   VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_YONETICILER PRIMARY KEY (YONETICI_ID)
);

-- Ornek veri
INSERT INTO YONETICILER (YONETICI_ID, AD, SOYAD, DEPARTMAN)
VALUES (1, 'Ahmet', 'Yilmaz', 'Yazilim');

INSERT INTO YONETICILER (YONETICI_ID, AD, SOYAD, DEPARTMAN)
VALUES (2, 'Ayse', 'Demir', 'Insan Kaynaklari');

COMMIT;
